import { UnifiedQuestion } from '@/types/question';

// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by migrate-problems.ts script
// Consolidates all MENSA questions from multiple sources

export interface ConsolidatedMensaQuestion extends UnifiedQuestion {
  subtype: string;
  title: string;
  answerKey: string;
  originalId: string;
  htmlTemplate?: string;
  problemNumber: number;
}

export const CONSOLIDATED_MENSA_QUESTIONS: ConsolidatedMensaQuestion[] = [
  {
    "id": "mensa_001",
    "problemNumber": 1,
    "category": "logical",
    "subtype": "set-theory",
    "difficulty": 5,
    "title": "論理推論 - set-theory",
    "question": "もしすべてのフライパンが金属製で、すべての金属製品が電気を通すなら、フライパンについて何が言えますか？",
    "options": [
      "フライパンは電気を通す",
      "フライパンは電気を通さない",
      "フライパンは時々電気を通す",
      "判断できない"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 60,
    "explanation": "三段論法の基本原理により、正解は「フライパンは電気を通す」",
    "originalId": "logical_real_1",
    "htmlTemplate": "problem-001-set-theory.html",
    "practiceDetails": {
      "immediateExplanation": "三段論法の基本原理により、正解は「フライパンは電気を通す」",
      "detailedSolution": "三段論法の基本原理により、正解は「フライパンは電気を通す」\n\n詳細解法：\n1. 前提条件を整理\n2. 論理規則を適用\n3. 結論を導出",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 論理的推論の誤り",
        "選択肢Bを選ぶ間違い: 論理的推論の誤り"
      ],
      "relatedConcepts": [
        "集合論",
        "論理学",
        "包含関係"
      ],
      "difficultyJustification": "MENSA入門レベル：基本的な論理思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "entry",
      "cognitiveSkills": [
        "論理的推論",
        "演繹的思考",
        "批判的思考"
      ]
    }
  },
  {
    "id": "mensa_002",
    "problemNumber": 2,
    "category": "logical",
    "subtype": "set-theory",
    "difficulty": 8,
    "title": "論理推論 - set-theory",
    "question": "「すべてのQはRである」「いくつかのPはQである」この2つが真の時、以下のうち必ず真となるのは？",
    "options": [
      "すべてのPはRである",
      "いくつかのPはRである",
      "すべてのRはPである",
      "いくつかのRはPである"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 90,
    "explanation": "三段論法の基本原理により、正解は「いくつかのPはRである」",
    "originalId": "logical_real_2",
    "htmlTemplate": "problem-002-set-theory.html",
    "practiceDetails": {
      "immediateExplanation": "三段論法の基本原理により、正解は「いくつかのPはRである」",
      "detailedSolution": "三段論法の基本原理により、正解は「いくつかのPはRである」\n\n詳細解法：\n1. 前提条件を整理\n2. 論理規則を適用\n3. 結論を導出",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 論理的推論の誤り",
        "選択肢Bを選ぶ間違い: 論理的推論の誤り"
      ],
      "relatedConcepts": [
        "集合論",
        "論理学",
        "包含関係"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "論理的推論",
        "演繹的思考",
        "批判的思考"
      ]
    }
  },
  {
    "id": "mensa_003",
    "problemNumber": 3,
    "category": "logical",
    "subtype": "conditional-logic",
    "difficulty": 12,
    "title": "論理推論 - conditional-logic",
    "question": "AはBよりも背が高い。CはAよりも背が低い。DはCよりも背が高いがBよりも背が低い。身長順序として正しいのは？",
    "options": [
      "A > D > C > B",
      "A > B > D > C",
      "A > C > D > B",
      "A > D > B > C"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 120,
    "explanation": "三段論法の基本原理により、正解は「A > B > D > C」",
    "originalId": "logical_real_3",
    "htmlTemplate": "problem-003-conditional-logic.html",
    "practiceDetails": {
      "immediateExplanation": "三段論法の基本原理により、正解は「A > B > D > C」",
      "detailedSolution": "三段論法の基本原理により、正解は「A > B > D > C」\n\n詳細解法：\n1. 前提条件を整理\n2. 論理規則を適用\n3. 結論を導出",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 論理的推論の誤り",
        "選択肢Bを選ぶ間違い: 論理的推論の誤り"
      ],
      "relatedConcepts": [
        "条件文",
        "推論",
        "論理演算"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "論理的推論",
        "演繹的思考",
        "批判的思考"
      ]
    }
  },
  {
    "id": "mensa_004",
    "problemNumber": 4,
    "category": "numerical",
    "subtype": "numerical",
    "difficulty": 6,
    "title": "数列完成 - numerical",
    "question": "次の数列の法則を見つけて、?に入る数字を答えてください: 1, 4, 9, 16, 25, ?",
    "options": [
      "30",
      "36",
      "35",
      "49"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 90,
    "explanation": "数列のパターンを分析すると、正解は「36」",
    "originalId": "numerical_real_1",
    "htmlTemplate": "problem-004-numerical.html",
    "practiceDetails": {
      "immediateExplanation": "数列のパターンを分析すると、正解は「36」",
      "detailedSolution": "数列のパターンを分析すると、正解は「36」\n\n詳細解法：\n1. 数列の差分を計算\n2. パターンを特定\n3. 次の項を予測",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 数列パターンの誤認識",
        "選択肢Bを選ぶ間違い: 数列パターンの誤認識"
      ],
      "relatedConcepts": [
        "数列",
        "パターン認識",
        "数学的帰納法"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "entry",
      "cognitiveSkills": [
        "パターン認識",
        "数学的思考",
        "帰納的推論"
      ]
    }
  },
  {
    "id": "mensa_005",
    "problemNumber": 5,
    "category": "numerical",
    "subtype": "numerical",
    "difficulty": 10,
    "title": "数列完成 - numerical",
    "question": "数列: 2, 6, 12, 20, 30, ? の次の数は？",
    "options": [
      "40",
      "42",
      "38",
      "44"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 90,
    "explanation": "数列のパターンを分析すると、正解は「42」",
    "originalId": "numerical_real_2",
    "htmlTemplate": "problem-005-numerical.html",
    "practiceDetails": {
      "immediateExplanation": "数列のパターンを分析すると、正解は「42」",
      "detailedSolution": "数列のパターンを分析すると、正解は「42」\n\n詳細解法：\n1. 数列の差分を計算\n2. パターンを特定\n3. 次の項を予測",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 数列パターンの誤認識",
        "選択肢Bを選ぶ間違い: 数列パターンの誤認識"
      ],
      "relatedConcepts": [
        "数列",
        "パターン認識",
        "数学的帰納法"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "数学的思考",
        "帰納的推論"
      ]
    }
  },
  {
    "id": "mensa_006",
    "problemNumber": 6,
    "category": "numerical",
    "subtype": "numerical",
    "difficulty": 14,
    "title": "数列完成 - numerical",
    "question": "3, 7, 15, 31, 63, ? この数列の次の項は？",
    "options": [
      "95",
      "127",
      "120",
      "135"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 120,
    "explanation": "数列のパターンを分析すると、正解は「127」",
    "originalId": "numerical_real_3",
    "htmlTemplate": "problem-006-numerical.html",
    "practiceDetails": {
      "immediateExplanation": "数列のパターンを分析すると、正解は「127」",
      "detailedSolution": "数列のパターンを分析すると、正解は「127」\n\n詳細解法：\n1. 数列の差分を計算\n2. パターンを特定\n3. 次の項を予測",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 数列パターンの誤認識",
        "選択肢Bを選ぶ間違い: 数列パターンの誤認識"
      ],
      "relatedConcepts": [
        "数列",
        "パターン認識",
        "数学的帰納法"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "数学的思考",
        "帰納的推論"
      ]
    }
  },
  {
    "id": "mensa_007",
    "problemNumber": 7,
    "category": "numerical",
    "subtype": "numerical",
    "difficulty": 16,
    "title": "数列完成 - numerical",
    "question": "フィボナッチ変形数列: 1, 1, 3, 5, 11, 21, ? 次の数は？",
    "options": [
      "43",
      "45",
      "41",
      "47"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 180,
    "explanation": "数列のパターンを分析すると、正解は「43」",
    "originalId": "numerical_real_4",
    "htmlTemplate": "problem-007-numerical.html",
    "practiceDetails": {
      "immediateExplanation": "数列のパターンを分析すると、正解は「43」",
      "detailedSolution": "数列のパターンを分析すると、正解は「43」\n\n詳細解法：\n1. 数列の差分を計算\n2. パターンを特定\n3. 次の項を予測",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 数列パターンの誤認識",
        "選択肢Bを選ぶ間違い: 数列パターンの誤認識"
      ],
      "relatedConcepts": [
        "数列",
        "パターン認識",
        "数学的帰納法"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "パターン認識",
        "数学的思考",
        "帰納的推論"
      ]
    }
  },
  {
    "id": "mensa_008",
    "problemNumber": 8,
    "category": "spatial",
    "subtype": "3d-rotation",
    "difficulty": 7,
    "title": "空間認識 - 3d-rotation",
    "question": "立方体を展開した図で、面Aの向かい側にある面はどれですか？\n[A][B]\n[C][D][E][F]",
    "options": [
      "面D",
      "面E",
      "面F",
      "面B"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 90,
    "explanation": "空間変換を考慮すると、正解は「面D」",
    "originalId": "spatial_real_1",
    "htmlTemplate": "problem-008-3d-rotation.html",
    "visualData": {
      "type": "cube",
      "data": "cube_net",
      "displayMode": "3d",
      "interactionMode": "interactive"
    },
    "practiceDetails": {
      "immediateExplanation": "空間変換を考慮すると、正解は「面D」",
      "detailedSolution": "空間変換を考慮すると、正解は「面D」\n\n詳細解法：\n1. 立体構造を分析\n2. 変換を適用\n3. 結果を確認",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 空間変換の誤解",
        "選択肢Bを選ぶ間違い: 空間変換の誤解"
      ],
      "relatedConcepts": [
        "空間幾何学",
        "行列変換",
        "四元数"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "entry",
      "cognitiveSkills": [
        "空間認識",
        "視覚的処理",
        "心的回転"
      ]
    }
  },
  {
    "id": "mensa_009",
    "problemNumber": 9,
    "category": "spatial",
    "subtype": "projection",
    "difficulty": 11,
    "title": "空間認識 - projection",
    "question": "正四面体を上から見た時の影の形は？",
    "options": [
      "正三角形",
      "正方形",
      "円",
      "六角形"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 120,
    "explanation": "空間変換を考慮すると、正解は「正三角形」",
    "originalId": "spatial_real_2",
    "htmlTemplate": "problem-009-projection.html",
    "practiceDetails": {
      "immediateExplanation": "空間変換を考慮すると、正解は「正三角形」",
      "detailedSolution": "空間変換を考慮すると、正解は「正三角形」\n\n詳細解法：\n1. 立体構造を分析\n2. 変換を適用\n3. 結果を確認",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 空間変換の誤解",
        "選択肢Bを選ぶ間違い: 空間変換の誤解"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "空間認識",
        "視覚的処理",
        "心的回転"
      ]
    }
  },
  {
    "id": "mensa_010",
    "problemNumber": 10,
    "category": "spatial",
    "subtype": "3d-rotation",
    "difficulty": 15,
    "title": "空間認識 - 3d-rotation",
    "question": "4次元立方体（テッセラクト）の頂点数は？",
    "options": [
      "8",
      "12",
      "16",
      "24"
    ],
    "correctAnswer": 2,
    "answerKey": "C",
    "timeLimit": 120,
    "explanation": "空間変換を考慮すると、正解は「16」",
    "originalId": "spatial_real_3",
    "htmlTemplate": "problem-010-3d-rotation.html",
    "practiceDetails": {
      "immediateExplanation": "空間変換を考慮すると、正解は「16」",
      "detailedSolution": "空間変換を考慮すると、正解は「16」\n\n詳細解法：\n1. 立体構造を分析\n2. 変換を適用\n3. 結果を確認",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 空間変換の誤解",
        "選択肢Bを選ぶ間違い: 空間変換の誤解"
      ],
      "relatedConcepts": [
        "空間幾何学",
        "行列変換",
        "四元数"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "空間認識",
        "視覚的処理",
        "心的回転"
      ]
    }
  },
  {
    "id": "mensa_011",
    "problemNumber": 11,
    "category": "matrix",
    "subtype": "distribution",
    "difficulty": 8,
    "title": "行列推論 - distribution",
    "question": "3×3行列で各行に○△□が1つずつ、各列に大中小が1つずつ含まれる。右下に入るのは？\n○大 △中 ？\n□中 ○小 △大\n△小 □大 ○中",
    "options": [
      "□小",
      "○大",
      "△中",
      "□中"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 90,
    "explanation": "問題の規則性から、正解は「□小」",
    "originalId": "matrix_real_1",
    "htmlTemplate": "problem-011-distribution.html",
    "visualData": {
      "type": "matrix",
      "data": "matrix_pattern",
      "displayMode": "static",
      "interactionMode": "display"
    },
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「□小」",
      "detailedSolution": "問題の規則性から、正解は「□小」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  },
  {
    "id": "mensa_012",
    "problemNumber": 12,
    "category": "matrix",
    "subtype": "rotation",
    "difficulty": 12,
    "title": "行列推論 - rotation",
    "question": "パターン行列：左上から時計回りに90度ずつ回転。最後のパターンは？\n↑ → ？\n← ↓ ↑\n？ ← ↓",
    "options": [
      "↓",
      "→",
      "↑",
      "←"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 120,
    "explanation": "問題の規則性から、正解は「↓」",
    "originalId": "matrix_real_2",
    "htmlTemplate": "problem-012-rotation.html",
    "visualData": {
      "type": "matrix",
      "data": "rotation_pattern",
      "displayMode": "static",
      "interactionMode": "interactive"
    },
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「↓」",
      "detailedSolution": "問題の規則性から、正解は「↓」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  },
  {
    "id": "mensa_013",
    "problemNumber": 13,
    "category": "matrix",
    "subtype": "rotation",
    "difficulty": 16,
    "title": "行列推論 - rotation",
    "question": "複合変換行列：図形が右に移動+拡大+回転の複合変換。次の変換は？",
    "options": [
      "移動のみ",
      "拡大のみ",
      "回転のみ",
      "3つの複合"
    ],
    "correctAnswer": 3,
    "answerKey": "D",
    "timeLimit": 180,
    "explanation": "問題の規則性から、正解は「3つの複合」",
    "originalId": "matrix_real_3",
    "htmlTemplate": "problem-013-rotation.html",
    "visualData": {
      "type": "matrix",
      "data": "complex_transformation",
      "displayMode": "static",
      "interactionMode": "interactive"
    },
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「3つの複合」",
      "detailedSolution": "問題の規則性から、正解は「3つの複合」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  },
  {
    "id": "mensa_014",
    "problemNumber": 14,
    "category": "pattern",
    "subtype": "classification",
    "difficulty": 6,
    "title": "パターン認識 - classification",
    "question": "医者：病院 = 教師：？",
    "options": [
      "学校",
      "生徒",
      "授業",
      "教科書"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 90,
    "explanation": "問題の規則性から、正解は「学校」",
    "originalId": "verbal_real_1",
    "htmlTemplate": "problem-014-classification.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「学校」",
      "detailedSolution": "問題の規則性から、正解は「学校」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "entry",
      "cognitiveSkills": [
        "パターン認識",
        "分類能力",
        "記憶処理"
      ]
    }
  },
  {
    "id": "mensa_015",
    "problemNumber": 15,
    "category": "pattern",
    "subtype": "classification",
    "difficulty": 9,
    "title": "パターン認識 - classification",
    "question": "原因：結果 = 種：？",
    "options": [
      "土",
      "水",
      "植物",
      "収穫"
    ],
    "correctAnswer": 2,
    "answerKey": "C",
    "timeLimit": 90,
    "explanation": "問題の規則性から、正解は「植物」",
    "originalId": "verbal_real_2",
    "htmlTemplate": "problem-015-classification.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「植物」",
      "detailedSolution": "問題の規則性から、正解は「植物」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "分類能力",
        "記憶処理"
      ]
    }
  },
  {
    "id": "mensa_016",
    "problemNumber": 16,
    "category": "pattern",
    "subtype": "classification",
    "difficulty": 13,
    "title": "パターン認識 - classification",
    "question": "「TOKYO」を「YOJKT」と変換する規則で「OSAKA」はどうなる？",
    "options": [
      "AKASO",
      "ASAKO",
      "AKAOS",
      "SAOAK"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 120,
    "explanation": "問題の規則性から、正解は「AKASO」",
    "originalId": "verbal_real_3",
    "htmlTemplate": "problem-016-classification.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「AKASO」",
      "detailedSolution": "問題の規則性から、正解は「AKASO」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "分類能力",
        "記憶処理"
      ]
    }
  },
  {
    "id": "mensa_017",
    "problemNumber": 17,
    "category": "matrix",
    "subtype": "progression",
    "difficulty": 10,
    "title": "行列推論 - progression",
    "question": "概念の包含関係：「すべてのバラは花である」「すべての花は植物である」から導けるのは？",
    "options": [
      "すべてのバラは植物である",
      "すべての植物はバラである",
      "いくつかの植物は花である",
      "判断できない"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 90,
    "explanation": "問題の規則性から、正解は「すべてのバラは植物である」",
    "originalId": "abstract_real_1",
    "htmlTemplate": "problem-017-progression.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「すべてのバラは植物である」",
      "detailedSolution": "問題の規則性から、正解は「すべてのバラは植物である」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  },
  {
    "id": "mensa_018",
    "problemNumber": 18,
    "category": "matrix",
    "subtype": "progression",
    "difficulty": 14,
    "title": "行列推論 - progression",
    "question": "メタパターン認識：A→B→C、D→E→F、G→？→I の？に入るのは？",
    "options": [
      "H",
      "J",
      "F",
      "K"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 120,
    "explanation": "問題の規則性から、正解は「H」",
    "originalId": "abstract_real_2",
    "htmlTemplate": "problem-018-progression.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「H」",
      "detailedSolution": "問題の規則性から、正解は「H」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  },
  {
    "id": "mensa_019",
    "problemNumber": 19,
    "category": "matrix",
    "subtype": "progression",
    "difficulty": 18,
    "title": "行列推論 - progression",
    "question": "高次関数的思考：f(x) = x+1, g(x) = 2x とすると f(g(3)) = ?",
    "options": [
      "6",
      "7",
      "8",
      "9"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 180,
    "explanation": "問題の規則性から、正解は「7」",
    "originalId": "abstract_real_3",
    "htmlTemplate": "problem-019-progression.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「7」",
      "detailedSolution": "問題の規則性から、正解は「7」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  },
  {
    "id": "mensa_020",
    "problemNumber": 20,
    "category": "pattern",
    "subtype": "shape-counting",
    "difficulty": 7,
    "title": "パターン認識 - shape-counting",
    "question": "次の数字を逆順で答えてください：7, 2, 9, 4, 1, 6",
    "options": [
      "6, 1, 4, 9, 2, 7",
      "7, 2, 9, 4, 1, 6",
      "1, 4, 9, 2, 7, 6",
      "6, 2, 1, 4, 9, 7"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 90,
    "explanation": "問題の規則性から、正解は「6, 1, 4, 9, 2, 7」",
    "originalId": "memory_real_1",
    "htmlTemplate": "problem-020-shape-counting.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「6, 1, 4, 9, 2, 7」",
      "detailedSolution": "問題の規則性から、正解は「6, 1, 4, 9, 2, 7」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "entry",
      "cognitiveSkills": [
        "パターン認識",
        "分類能力",
        "記憶処理"
      ]
    }
  },
  {
    "id": "mensa_021",
    "problemNumber": 21,
    "category": "pattern",
    "subtype": "shape-counting",
    "difficulty": 11,
    "title": "パターン認識 - shape-counting",
    "question": "次の文字列を覚えて、2文字目、4文字目、6文字目を順に答えてください：PQRSTU",
    "options": [
      "Q, S, U",
      "P, R, T",
      "R, T, U",
      "Q, T, S"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 120,
    "explanation": "問題の規則性から、正解は「Q, S, U」",
    "originalId": "memory_real_2",
    "htmlTemplate": "problem-021-shape-counting.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「Q, S, U」",
      "detailedSolution": "問題の規則性から、正解は「Q, S, U」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "分類能力",
        "記憶処理"
      ]
    }
  },
  {
    "id": "mensa_022",
    "problemNumber": 22,
    "category": "pattern",
    "subtype": "shape-counting",
    "difficulty": 15,
    "title": "パターン認識 - shape-counting",
    "question": "N-back記憶課題：この数列で2つ前と同じ数字はどれ？ 3, 7, 3, 9, 7, 1, 9",
    "options": [
      "位置3の3",
      "位置5の7",
      "位置7の9",
      "該当なし"
    ],
    "correctAnswer": 2,
    "answerKey": "C",
    "timeLimit": 120,
    "explanation": "問題の規則性から、正解は「位置7の9」",
    "originalId": "memory_real_3",
    "htmlTemplate": "problem-022-shape-counting.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「位置7の9」",
      "detailedSolution": "問題の規則性から、正解は「位置7の9」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "パターン認識",
        "分類能力",
        "記憶処理"
      ]
    }
  },
  {
    "id": "mensa_023",
    "problemNumber": 23,
    "category": "logical",
    "subtype": "boolean-operations",
    "difficulty": 17,
    "title": "論理推論 - boolean-operations",
    "question": "論理パズル：A、B、C、Dの4人がいて、正直者と嘘つきがいる。A:「Bは嘘つき」、B:「Cは正直者」、C:「Dは嘘つき」、D:「Aは正直者」。正直者は何人？",
    "options": [
      "1人",
      "2人",
      "3人",
      "4人"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 180,
    "explanation": "三段論法の基本原理により、正解は「2人」",
    "originalId": "advanced_1",
    "htmlTemplate": "problem-023-boolean-operations.html",
    "practiceDetails": {
      "immediateExplanation": "三段論法の基本原理により、正解は「2人」",
      "detailedSolution": "三段論法の基本原理により、正解は「2人」\n\n詳細解法：\n1. 前提条件を整理\n2. 論理規則を適用\n3. 結論を導出",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 論理的推論の誤り",
        "選択肢Bを選ぶ間違い: 論理的推論の誤り"
      ],
      "relatedConcepts": [
        "ブール代数",
        "真理値表",
        "論理回路"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "論理的推論",
        "演繹的思考",
        "批判的思考"
      ]
    }
  },
  {
    "id": "mensa_024",
    "problemNumber": 24,
    "category": "numerical",
    "subtype": "numerical",
    "difficulty": 18,
    "title": "数列完成 - numerical",
    "question": "数学的帰納法パターン：1, 8, 27, 64, 125, ? (各項の関係性を見つけて)",
    "options": [
      "186",
      "196",
      "216",
      "256"
    ],
    "correctAnswer": 2,
    "answerKey": "C",
    "timeLimit": 180,
    "explanation": "数列のパターンを分析すると、正解は「216」",
    "originalId": "advanced_2",
    "htmlTemplate": "problem-024-numerical.html",
    "practiceDetails": {
      "immediateExplanation": "数列のパターンを分析すると、正解は「216」",
      "detailedSolution": "数列のパターンを分析すると、正解は「216」\n\n詳細解法：\n1. 数列の差分を計算\n2. パターンを特定\n3. 次の項を予測",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 数列パターンの誤認識",
        "選択肢Bを選ぶ間違い: 数列パターンの誤認識"
      ],
      "relatedConcepts": [
        "数列",
        "パターン認識",
        "数学的帰納法"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "パターン認識",
        "数学的思考",
        "帰納的推論"
      ]
    }
  },
  {
    "id": "mensa_025",
    "problemNumber": 25,
    "category": "spatial",
    "subtype": "3d-rotation",
    "difficulty": 19,
    "title": "空間認識 - 3d-rotation",
    "question": "超立方体（5次元）の面の数は？",
    "options": [
      "10",
      "32",
      "40",
      "80"
    ],
    "correctAnswer": 2,
    "answerKey": "C",
    "timeLimit": 180,
    "explanation": "空間変換を考慮すると、正解は「40」",
    "originalId": "advanced_3",
    "htmlTemplate": "problem-025-3d-rotation.html",
    "practiceDetails": {
      "immediateExplanation": "空間変換を考慮すると、正解は「40」",
      "detailedSolution": "空間変換を考慮すると、正解は「40」\n\n詳細解法：\n1. 立体構造を分析\n2. 変換を適用\n3. 結果を確認",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 空間変換の誤解",
        "選択肢Bを選ぶ間違い: 空間変換の誤解"
      ],
      "relatedConcepts": [
        "空間幾何学",
        "行列変換",
        "四元数"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "genius",
      "cognitiveSkills": [
        "空間認識",
        "視覚的処理",
        "心的回転"
      ]
    }
  },
  {
    "id": "mensa_026",
    "problemNumber": 26,
    "category": "matrix",
    "subtype": "progression",
    "difficulty": 20,
    "title": "行列推論 - progression",
    "question": "メタ論理：「この文は偽である」という文の真偽は？",
    "options": [
      "真",
      "偽",
      "不定",
      "パラドックス"
    ],
    "correctAnswer": 3,
    "answerKey": "D",
    "timeLimit": 180,
    "explanation": "問題の規則性から、正解は「パラドックス」",
    "originalId": "advanced_4",
    "htmlTemplate": "problem-026-progression.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「パラドックス」",
      "detailedSolution": "問題の規則性から、正解は「パラドックス」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "genius",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  },
  {
    "id": "mensa_027",
    "problemNumber": 27,
    "category": "numerical",
    "subtype": "numerical",
    "difficulty": 9,
    "title": "数列完成 - numerical",
    "question": "2, 3, 5, 8, 13, ? この数列の次の項は？",
    "options": [
      "18",
      "21",
      "20",
      "19"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 90,
    "explanation": "数列のパターンを分析すると、正解は「21」",
    "originalId": "medium_1",
    "htmlTemplate": "problem-027-numerical.html",
    "practiceDetails": {
      "immediateExplanation": "数列のパターンを分析すると、正解は「21」",
      "detailedSolution": "数列のパターンを分析すると、正解は「21」\n\n詳細解法：\n1. 数列の差分を計算\n2. パターンを特定\n3. 次の項を予測",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 数列パターンの誤認識",
        "選択肢Bを選ぶ間違い: 数列パターンの誤認識"
      ],
      "relatedConcepts": [
        "数列",
        "パターン認識",
        "数学的帰納法"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "数学的思考",
        "帰納的推論"
      ]
    }
  },
  {
    "id": "mensa_028",
    "problemNumber": 28,
    "category": "logical",
    "subtype": "boolean-operations",
    "difficulty": 10,
    "title": "論理推論 - boolean-operations",
    "question": "条件推論：「雨が降れば試合は中止」「試合は中止になった」から導けるのは？",
    "options": [
      "雨が降った",
      "雨は降らなかった",
      "判断できない",
      "試合は開催された"
    ],
    "correctAnswer": 2,
    "answerKey": "C",
    "timeLimit": 90,
    "explanation": "三段論法の基本原理により、正解は「判断できない」",
    "originalId": "medium_2",
    "htmlTemplate": "problem-028-boolean-operations.html",
    "practiceDetails": {
      "immediateExplanation": "三段論法の基本原理により、正解は「判断できない」",
      "detailedSolution": "三段論法の基本原理により、正解は「判断できない」\n\n詳細解法：\n1. 前提条件を整理\n2. 論理規則を適用\n3. 結論を導出",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 論理的推論の誤り",
        "選択肢Bを選ぶ間違い: 論理的推論の誤り"
      ],
      "relatedConcepts": [
        "ブール代数",
        "真理値表",
        "論理回路"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "論理的推論",
        "演繹的思考",
        "批判的思考"
      ]
    }
  },
  {
    "id": "mensa_029",
    "problemNumber": 29,
    "category": "spatial",
    "subtype": "projection",
    "difficulty": 9,
    "title": "空間認識 - projection",
    "question": "サイコロの相対する面の数の和は常に7。1の向かいが6、2の向かいが5なら、3の向かいは？",
    "options": [
      "4",
      "5",
      "6",
      "1"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 90,
    "explanation": "空間変換を考慮すると、正解は「4」",
    "originalId": "medium_3",
    "htmlTemplate": "problem-029-projection.html",
    "practiceDetails": {
      "immediateExplanation": "空間変換を考慮すると、正解は「4」",
      "detailedSolution": "空間変換を考慮すると、正解は「4」\n\n詳細解法：\n1. 立体構造を分析\n2. 変換を適用\n3. 結果を確認",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 空間変換の誤解",
        "選択肢Bを選ぶ間違い: 空間変換の誤解"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "空間認識",
        "視覚的処理",
        "心的回転"
      ]
    }
  },
  {
    "id": "mensa_030",
    "problemNumber": 30,
    "category": "pattern",
    "subtype": "classification",
    "difficulty": 8,
    "title": "パターン認識 - classification",
    "question": "語彙の関係：「楽観的」の反対語として最も適切なのは？",
    "options": [
      "悲観的",
      "現実的",
      "慎重",
      "消極的"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 90,
    "explanation": "問題の規則性から、正解は「悲観的」",
    "originalId": "medium_4",
    "htmlTemplate": "problem-030-classification.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「悲観的」",
      "detailedSolution": "問題の規則性から、正解は「悲観的」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "分類能力",
        "記憶処理"
      ]
    }
  },
  {
    "id": "mensa_031",
    "problemNumber": 31,
    "category": "logical",
    "subtype": "set-theory",
    "difficulty": 6,
    "title": "論理推論 - set-theory",
    "question": "すべてのバラは花である。すべての花は美しい。したがって、すべてのバラは美しい。この論理構造と同じものはどれか？",
    "options": [
      "すべての鳥は動物である。すべての動物は生き物である。したがって、すべての鳥は生き物である。",
      "いくつかの車は赤い。いくつかの赤いものは高価である。したがって、いくつかの車は高価である。",
      "すべての学生は若い。田中は学生である。したがって、田中は若い。",
      "いくつかの本は厚い。すべての厚い本は重い。したがって、いくつかの本は重い。"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 90,
    "explanation": "三段論法の基本原理により、正解は「すべての鳥は動物である。すべての動物は生き物である。したがって、すべての鳥は生き物である。」",
    "originalId": "logic_001",
    "htmlTemplate": "problem-031-set-theory.html",
    "practiceDetails": {
      "immediateExplanation": "三段論法の基本原理により、正解は「すべての鳥は動物である。すべての動物は生き物である。したがって、すべての鳥は生き物である。」",
      "detailedSolution": "三段論法の基本原理により、正解は「すべての鳥は動物である。すべての動物は生き物である。したがって、すべての鳥は生き物である。」\n\n詳細解法：\n1. 前提条件を整理\n2. 論理規則を適用\n3. 結論を導出",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 論理的推論の誤り",
        "選択肢Bを選ぶ間違い: 論理的推論の誤り"
      ],
      "relatedConcepts": [
        "集合論",
        "論理学",
        "包含関係"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "entry",
      "cognitiveSkills": [
        "論理的推論",
        "演繹的思考",
        "批判的思考"
      ]
    }
  },
  {
    "id": "mensa_032",
    "problemNumber": 32,
    "category": "logical",
    "subtype": "set-theory",
    "difficulty": 12,
    "title": "論理推論 - set-theory",
    "question": "5人の友人A、B、C、D、Eが一列に並んでいる。以下の条件をすべて満たす配置はどれか？\n・AはBの左側にいる\n・CはDの右側にいる\n・BはEより右側にいる\n・DはAより左側にいる",
    "options": [
      "D-C-A-E-B",
      "D-A-C-E-B",
      "C-D-A-E-B",
      "D-A-E-C-B"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 120,
    "explanation": "三段論法の基本原理により、正解は「D-C-A-E-B」",
    "originalId": "logic_002",
    "htmlTemplate": "problem-032-set-theory.html",
    "practiceDetails": {
      "immediateExplanation": "三段論法の基本原理により、正解は「D-C-A-E-B」",
      "detailedSolution": "三段論法の基本原理により、正解は「D-C-A-E-B」\n\n詳細解法：\n1. 前提条件を整理\n2. 論理規則を適用\n3. 結論を導出",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 論理的推論の誤り",
        "選択肢Bを選ぶ間違い: 論理的推論の誤り"
      ],
      "relatedConcepts": [
        "集合論",
        "論理学",
        "包含関係"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "論理的推論",
        "演繹的思考",
        "批判的思考"
      ]
    }
  },
  {
    "id": "mensa_033",
    "problemNumber": 33,
    "category": "logical",
    "subtype": "boolean-operations",
    "difficulty": 18,
    "title": "論理推論 - boolean-operations",
    "question": "「真実を語る人」と「嘘をつく人」が混在する島で、3人に出会った。\nA：「私たちの中に真実を語る人は最低1人いる」\nB：「私たちの中に嘘をつく人は最低1人いる」\nC：「私たちの中に嘘をつく人は最低2人いる」\n真実を語る人は何人いるか？",
    "options": [
      "1人",
      "2人",
      "3人",
      "判定不可能"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 180,
    "explanation": "三段論法の基本原理により、正解は「2人」",
    "originalId": "logic_003",
    "htmlTemplate": "problem-033-boolean-operations.html",
    "practiceDetails": {
      "immediateExplanation": "三段論法の基本原理により、正解は「2人」",
      "detailedSolution": "三段論法の基本原理により、正解は「2人」\n\n詳細解法：\n1. 前提条件を整理\n2. 論理規則を適用\n3. 結論を導出",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 論理的推論の誤り",
        "選択肢Bを選ぶ間違い: 論理的推論の誤り"
      ],
      "relatedConcepts": [
        "ブール代数",
        "真理値表",
        "論理回路"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "論理的推論",
        "演繹的思考",
        "批判的思考"
      ]
    }
  },
  {
    "id": "mensa_034",
    "problemNumber": 34,
    "category": "numerical",
    "subtype": "numerical",
    "difficulty": 8,
    "title": "数列完成 - numerical",
    "question": "数列：2, 6, 18, 54, ?, 486\n?に入る数字は？",
    "options": [
      "108",
      "162",
      "216",
      "324"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 90,
    "explanation": "数列のパターンを分析すると、正解は「162」",
    "originalId": "num_001",
    "htmlTemplate": "problem-034-numerical.html",
    "practiceDetails": {
      "immediateExplanation": "数列のパターンを分析すると、正解は「162」",
      "detailedSolution": "数列のパターンを分析すると、正解は「162」\n\n詳細解法：\n1. 数列の差分を計算\n2. パターンを特定\n3. 次の項を予測",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 数列パターンの誤認識",
        "選択肢Bを選ぶ間違い: 数列パターンの誤認識"
      ],
      "relatedConcepts": [
        "数列",
        "パターン認識",
        "数学的帰納法"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "数学的思考",
        "帰納的推論"
      ]
    }
  },
  {
    "id": "mensa_035",
    "problemNumber": 35,
    "category": "numerical",
    "subtype": "numerical",
    "difficulty": 14,
    "title": "数列完成 - numerical",
    "question": "数列：1, 1, 2, 3, 5, 8, 13, 21, ?, 55\n?に入る数字は？",
    "options": [
      "29",
      "34",
      "38",
      "42"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 120,
    "explanation": "数列のパターンを分析すると、正解は「34」",
    "originalId": "num_002",
    "htmlTemplate": "problem-035-numerical.html",
    "practiceDetails": {
      "immediateExplanation": "数列のパターンを分析すると、正解は「34」",
      "detailedSolution": "数列のパターンを分析すると、正解は「34」\n\n詳細解法：\n1. 数列の差分を計算\n2. パターンを特定\n3. 次の項を予測",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 数列パターンの誤認識",
        "選択肢Bを選ぶ間違い: 数列パターンの誤認識"
      ],
      "relatedConcepts": [
        "数列",
        "パターン認識",
        "数学的帰納法"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "数学的思考",
        "帰納的推論"
      ]
    }
  },
  {
    "id": "mensa_036",
    "problemNumber": 36,
    "category": "numerical",
    "subtype": "numerical",
    "difficulty": 20,
    "title": "数列完成 - numerical",
    "question": "数列：2, 6, 30, 210, 2310, ?\n次の項は？",
    "options": [
      "30030",
      "32310",
      "46200",
      "60060"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 180,
    "explanation": "数列のパターンを分析すると、正解は「30030」",
    "originalId": "num_003",
    "htmlTemplate": "problem-036-numerical.html",
    "practiceDetails": {
      "immediateExplanation": "数列のパターンを分析すると、正解は「30030」",
      "detailedSolution": "数列のパターンを分析すると、正解は「30030」\n\n詳細解法：\n1. 数列の差分を計算\n2. パターンを特定\n3. 次の項を予測",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 数列パターンの誤認識",
        "選択肢Bを選ぶ間違い: 数列パターンの誤認識"
      ],
      "relatedConcepts": [
        "数列",
        "パターン認識",
        "数学的帰納法"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "genius",
      "cognitiveSkills": [
        "パターン認識",
        "数学的思考",
        "帰納的推論"
      ]
    }
  },
  {
    "id": "mensa_037",
    "problemNumber": 37,
    "category": "spatial",
    "subtype": "3d-rotation",
    "difficulty": 10,
    "title": "空間認識 - 3d-rotation",
    "question": "立方体を左に90度回転させたとき、前面に見える面はどれか？",
    "options": [
      "A",
      "B",
      "C",
      "反対面"
    ],
    "correctAnswer": 2,
    "answerKey": "C",
    "timeLimit": 90,
    "explanation": "空間変換を考慮すると、正解は「C」",
    "originalId": "spatial_001",
    "htmlTemplate": "problem-037-3d-rotation.html",
    "visualData": {
      "type": "cube",
      "data": {
        "type": "cube_rotation",
        "initial_state": {
          "front": "A",
          "top": "B",
          "right": "C",
          "back": "D",
          "bottom": "E",
          "left": "F"
        }
      },
      "displayMode": "3d",
      "interactionMode": "interactive"
    },
    "practiceDetails": {
      "immediateExplanation": "空間変換を考慮すると、正解は「C」",
      "detailedSolution": "空間変換を考慮すると、正解は「C」\n\n詳細解法：\n1. 立体構造を分析\n2. 変換を適用\n3. 結果を確認",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 空間変換の誤解",
        "選択肢Bを選ぶ間違い: 空間変換の誤解"
      ],
      "relatedConcepts": [
        "空間幾何学",
        "行列変換",
        "四元数"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "空間認識",
        "視覚的処理",
        "心的回転"
      ]
    }
  },
  {
    "id": "mensa_038",
    "problemNumber": 38,
    "category": "spatial",
    "subtype": "3d-rotation",
    "difficulty": 16,
    "title": "空間認識 - 3d-rotation",
    "question": "4次元超立方体（テッサラクト）を3次元空間に投影したとき、頂点の数はいくつか？",
    "options": [
      "8",
      "12",
      "16",
      "24"
    ],
    "correctAnswer": 2,
    "answerKey": "C",
    "timeLimit": 180,
    "explanation": "空間変換を考慮すると、正解は「16」",
    "originalId": "spatial_002",
    "htmlTemplate": "problem-038-3d-rotation.html",
    "practiceDetails": {
      "immediateExplanation": "空間変換を考慮すると、正解は「16」",
      "detailedSolution": "空間変換を考慮すると、正解は「16」\n\n詳細解法：\n1. 立体構造を分析\n2. 変換を適用\n3. 結果を確認",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 空間変換の誤解",
        "選択肢Bを選ぶ間違い: 空間変換の誤解"
      ],
      "relatedConcepts": [
        "空間幾何学",
        "行列変換",
        "四元数"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "空間認識",
        "視覚的処理",
        "心的回転"
      ]
    }
  },
  {
    "id": "mensa_039",
    "problemNumber": 39,
    "category": "matrix",
    "subtype": "rotation",
    "difficulty": 12,
    "title": "行列推論 - rotation",
    "question": "3×3行列のパターンを分析し、空欄に入る図形を選択してください。\n[各行で図形が時計回りに90度ずつ回転]",
    "options": [
      "右向き三角形",
      "下向き三角形",
      "左向き三角形",
      "上向き三角形"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 120,
    "explanation": "問題の規則性から、正解は「下向き三角形」",
    "originalId": "matrix_001",
    "htmlTemplate": "problem-039-rotation.html",
    "visualData": {
      "type": "matrix",
      "data": "raven_matrix",
      "displayMode": "static",
      "interactionMode": "interactive"
    },
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「下向き三角形」",
      "detailedSolution": "問題の規則性から、正解は「下向き三角形」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  },
  {
    "id": "mensa_040",
    "problemNumber": 40,
    "category": "pattern",
    "subtype": "classification",
    "difficulty": 9,
    "title": "パターン認識 - classification",
    "question": "次の類推関係を完成させてください：\n「本：図書館 = 絵画：？」",
    "options": [
      "美術館",
      "キャンバス",
      "額縁",
      "画家"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 90,
    "explanation": "問題の規則性から、正解は「美術館」",
    "originalId": "verbal_001",
    "htmlTemplate": "problem-040-classification.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「美術館」",
      "detailedSolution": "問題の規則性から、正解は「美術館」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA標準レベル：中級推論能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "分類能力",
        "記憶処理"
      ]
    }
  },
  {
    "id": "mensa_041",
    "problemNumber": 41,
    "category": "matrix",
    "subtype": "progression",
    "difficulty": 15,
    "title": "行列推論 - progression",
    "question": "抽象的規則：図形Aに変換Tを適用すると図形Bになる。同じ変換Tを図形Cに適用した結果は？",
    "options": [
      "選択肢1",
      "選択肢2",
      "選択肢3",
      "選択肢4"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 120,
    "explanation": "問題の規則性から、正解は「選択肢2」",
    "originalId": "abstract_001",
    "htmlTemplate": "problem-041-progression.html",
    "visualData": {
      "type": "matrix",
      "data": "abstract_transformation",
      "displayMode": "static",
      "interactionMode": "display"
    },
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「選択肢2」",
      "detailedSolution": "問題の規則性から、正解は「選択肢2」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "expert",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  },
  {
    "id": "mensa_042",
    "problemNumber": 42,
    "category": "pattern",
    "subtype": "shape-counting",
    "difficulty": 11,
    "title": "パターン認識 - shape-counting",
    "question": "N-back課題：以下の図形列で、2つ前と同じ図形はどの位置にありますか？\n○△□◇○★□○",
    "options": [
      "位置6",
      "位置7",
      "位置8",
      "該当なし"
    ],
    "correctAnswer": 2,
    "answerKey": "C",
    "timeLimit": 120,
    "explanation": "問題の規則性から、正解は「位置8」",
    "originalId": "memory_001",
    "htmlTemplate": "problem-042-shape-counting.html",
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「位置8」",
      "detailedSolution": "問題の規則性から、正解は「位置8」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA上級レベル：高度な抽象思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "standard",
      "cognitiveSkills": [
        "パターン認識",
        "分類能力",
        "記憶処理"
      ]
    }
  },
  {
    "id": "mensa_043",
    "problemNumber": 43,
    "category": "logical",
    "subtype": "set-theory",
    "difficulty": 5,
    "title": "論理推論 - set-theory",
    "question": "すべての花は美しい。すべてのバラは花である。したがって：",
    "options": [
      "すべてのバラは美しい",
      "すべての美しいものはバラである",
      "いくつかの花はバラではない",
      "美しくないバラもある"
    ],
    "correctAnswer": 0,
    "answerKey": "A",
    "timeLimit": 60,
    "explanation": "三段論法の基本原理により、正解は「すべてのバラは美しい」",
    "originalId": "logic_exp_1",
    "htmlTemplate": "problem-043-set-theory.html",
    "practiceDetails": {
      "immediateExplanation": "三段論法の基本原理により、正解は「すべてのバラは美しい」",
      "detailedSolution": "三段論法の基本原理により、正解は「すべてのバラは美しい」\n\n詳細解法：\n1. 前提条件を整理\n2. 論理規則を適用\n3. 結論を導出",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 論理的推論の誤り",
        "選択肢Bを選ぶ間違い: 論理的推論の誤り"
      ],
      "relatedConcepts": [
        "集合論",
        "論理学",
        "包含関係"
      ],
      "difficultyJustification": "MENSA入門レベル：基本的な論理思考"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "entry",
      "cognitiveSkills": [
        "論理的推論",
        "演繹的思考",
        "批判的思考"
      ]
    }
  },
  {
    "id": "mensa_044",
    "problemNumber": 44,
    "category": "matrix",
    "subtype": "distribution",
    "difficulty": 20,
    "title": "行列推論 - distribution",
    "question": "最終チャレンジ：4×4行列での複合パターン認識。右下の要素は？\n○● ●○ ○● ？\n●○ ○● ●○ ○●\n○● ●○ ○● ●○\n●○ ○● ●○ ？",
    "options": [
      "○●",
      "●○",
      "○○",
      "●●"
    ],
    "correctAnswer": 1,
    "answerKey": "B",
    "timeLimit": 180,
    "explanation": "問題の規則性から、正解は「●○」",
    "originalId": "final_challenge",
    "htmlTemplate": "problem-044-distribution.html",
    "visualData": {
      "type": "matrix",
      "data": "complex_matrix",
      "displayMode": "static",
      "interactionMode": "display"
    },
    "practiceDetails": {
      "immediateExplanation": "問題の規則性から、正解は「●○」",
      "detailedSolution": "問題の規則性から、正解は「●○」",
      "commonMistakes": [
        "選択肢Aを選ぶ間違い: 問題解釈の誤り",
        "選択肢Bを選ぶ間違い: 問題解釈の誤り"
      ],
      "relatedConcepts": [
        "認知科学",
        "パターン認識"
      ],
      "difficultyJustification": "MENSA天才レベル：極めて高度な認知能力"
    },
    "mensaInfo": {
      "source": "MENSA International",
      "mensaLevel": "genius",
      "cognitiveSkills": [
        "抽象的推論",
        "システム思考",
        "関係性理解"
      ]
    }
  }
];

// Utility functions
export function getProblemById(id: string): ConsolidatedMensaQuestion | undefined {
  return CONSOLIDATED_MENSA_QUESTIONS.find(q => q.id === id);
}

export function getProblemsByCategory(category: string): ConsolidatedMensaQuestion[] {
  return CONSOLIDATED_MENSA_QUESTIONS.filter(q => q.category === category);
}

export function getProblemsByDifficulty(min: number, max: number): ConsolidatedMensaQuestion[] {
  return CONSOLIDATED_MENSA_QUESTIONS.filter(q => q.difficulty >= min && q.difficulty <= max);
}

export function getProblemsBySubtype(subtype: string): ConsolidatedMensaQuestion[] {
  return CONSOLIDATED_MENSA_QUESTIONS.filter(q => q.subtype === subtype);
}

export function getRandomProblems(count: number): ConsolidatedMensaQuestion[] {
  const shuffled = [...CONSOLIDATED_MENSA_QUESTIONS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

export function getProblemStats() {
  const byCategory = CONSOLIDATED_MENSA_QUESTIONS.reduce((acc, q) => {
    acc[q.category] = (acc[q.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  
  const byDifficulty = CONSOLIDATED_MENSA_QUESTIONS.reduce((acc, q) => {
    const level = q.difficulty <= 7 ? 'easy' : q.difficulty <= 14 ? 'medium' : q.difficulty <= 18 ? 'hard' : 'expert';
    acc[level] = (acc[level] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  
  return {
    total: CONSOLIDATED_MENSA_QUESTIONS.length,
    byCategory,
    byDifficulty,
    averageDifficulty: CONSOLIDATED_MENSA_QUESTIONS.reduce((sum, q) => sum + q.difficulty, 0) / CONSOLIDATED_MENSA_QUESTIONS.length
  };
}